// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DotNet6WebApp.DBModels
{
    public partial class Users
    {
        public int Id { get; set; }
        public string Acc { get; set; }
        public string Pass { get; set; }
        public bool State { get; set; }
        public int LoginCount { get; set; }
        public DateTime? ModifyDate { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}